project:
  type: website
  output-dir: docs

website:
  title: "Jinii"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: About
      - href: about.qmd
      - href: posts/index.qmd
        text: Blog
    

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



