---
title: "LS 빅데이터 스쿨 Homework 7"
author: Jinii
date: '2024-09-02'
categories: [bigdata]
jupyter: python3
---

## ADP 표본점수
2022년에 실시 된 ADP 실기 시험의 통계파트 표준점수는 평균이 30, 표준편차가 5인 정규분포를 따른다고 한다.

# 1. ADP 실기 시험의 통계파트 표준점수의 밀도함수를 그려보세요.
```{python}
import numpy as np
from scipy.stats import norm
import matplotlib.pyplot as plt

x=np.arange(15, 45, 0.1)
y=norm.pdf(x, loc=30, scale=5)
plt.plot(x, y)
```

# 2. ADP 수험생을 임의로 1명을 선택하여 통계 점수를 조회했을때 45점 보다 높은 점수를 받았을 확률을 구하세요.
```{python}
1-norm.cdf(45, loc=30, scale=5)
```

# 3. 슬통이는 상위 10%에 해당하는 점수를 얻었다고 한다면, 슬통이의 점수는 얼마인지 계산해보세요.
```{python}
norm.ppf(0.9, loc=30, scale=5)
```

# 4. 슬기로운 통계생활의 해당 회차 수강생은 16명이었다고 한다. 16명의 통계 파트 점수를 평균내었을 때, 이 평균값이 따르는 분포의 확률밀도 함수를 1번의 그래프와 겹쳐 그려보세요.
```{python}
# 기존 그래프
x=np.arange(15, 45, 0.1)
y=norm.pdf(x, loc=30, scale=5)
plt.plot(x, y)

# 새로운 그래프
y2=norm.pdf(x, loc=30, scale=5/np.sqrt(16))
plt.plot(x, y2, color='red')
```

# 5. 슬기로운 통계생활 ADP 반 수강생들의 통계점수를 평균내었다고 할 때, 이 값이 38점보다 높게 나올 확률을 구하세요.
```{python}
1-norm.cdf(38, loc=30, scale=5/np.sqrt(16))
```

## 카이제곱분포와 표본분산
자유도가 𝑘인 카이제곱분포를 따르는 확률변수 𝑋 를 𝑋 ∼ 𝜒2(𝑘)과 같이 나타내고,
이 확률변수의 확률밀도함수는 다음과 같습니다.
𝑓𝑋(𝑥; 𝑘) = 1/((2𝑘/2Γ(𝑘/2))**𝑥𝑘/2−1𝑒−𝑥/2)
다음의 물음에 답하세요.

# 1. 자유도가 4인 카이제곱분포의 확률밀도함수를 그려보세요.
```{python}
from scipy.stats import chi2, norm
x=np.linspace(0, 20, 1000)
pdf=chi2.pdf(x, 4)
plt.plot(x, pdf)

```

# 2. 다음의 확률을 구해보세요. 𝑃 (3 ≤ 𝑋 ≤ 5)
```{python}
chi2.cdf(5, 4) - chi2.cdf(3, 4)
```

# 3. 자유도가 4인 카이제곱분포에서 크기가 1000인 표본을 뽑은 후, 히스토그램을 그려보세요.
```{python}
np.random.seed(20240902)
data=chi2.rvs(4, size=1000)
plt.hist(data, bins=50, density=True, color='black', edgecolor='blue')

```

# 4. 자유도가 4인 카이제곱분포를 따르는 확률변수에서 나올 수 있는 값 중 상위 5%에 해당하는 값은 얼마인지 계산해보세요.
```{python}
chi2.ppf(0.95, 4)
```

# 5. 3번에서 뽑힌 표본값들 중 상위 5%에 위치한 표본의 값은 얼마인가요?
```{python}
np.percentile(data, 95)
```

# 6. 평균이 3, 표준편차가 2인 정규분포를 따르는 확률변수에서 크기가 20인 표본, 𝑥1, ..., 𝑥20,을 뽑은 후 표본분산을 계산한 것을 𝑠21이라 생각해보죠. 다음을 수행해보세요!
• 같은 방법으로 500개의 𝑠2 들, 𝑠21
, 𝑠22
, ..., 𝑠2
500 발생시킵니다.
• 발생한 500개의 𝑠2 들 각각에 4.75를 곱하고, 그것들의 히스토그램을 그려보세요. (히스토그램
을 그릴 때 probability = TRUE 옵션을 사용해서 그릴 것)
• 위에서 그린 히스토그램에 자유도가 19인 카이제곱분포 확률밀도함수를 겹쳐그려보세요.
```{python}
np.random.seed(20240902)
var_samples=[]

for i in range (500):
    x=norm.rvs(loc=3, scale=2, size=20)
    var_samples.append(np.var(x, ddof=1))

scaled_var_samples=np.array(var_samples)

plt.hist(scaled_var_samples, bins=50, density=True, color='lightblue',
        edgecolor='black')

x = np.linspace(0, max(scaled_var_samples), 1000)
pdf_chi19=chi2.pdf(x, df=19)

plt.plot(x, pdf_chi19, 'r--', linewidth=2);
plt.legend(['histogram', 'df 19 chisquare dist'], loc='upper right');
plt.show()
```
